MODEL_NAME: CIL_multiview_actor_critic
LEARNING_RATE: 8.0e-04
EPOCHS: 80
batch_size: 750
num_workers: 2
seed: 0
SAVE_PATH: ./models/CILv2_multiview/_results/checkpoints/
data_path: ./models/CILv2_multiview/data/
train_dataset_names: 
- Roach_carla0913_fps10_dense_normalcamera_T1_dense_3cam 
val_dataset_names: 
- Roach_LBCRoutes_3cam_valid
