MODEL_NAME: CIL_multiview_actor_critic
LEARNING_RATE: 8.0e-05
loss: l1 # l1 for l1 loss otherwise is l2
EPOCHS: 50
batch_size: 1
num_workers: 4
seed: 0
SAVE_PATH: ./models/CILv2_multiview/_results/checkpoints/
data_path: ./models/CILv2_multiview/data/
train_dataset_names:
- smalltrain1/RouteScenario_0000
val_dataset_names:
- smalltrain1/RouteScenario_0000
